name: Sync Upstream Repo

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          ref: sync-bot  # Work with the sync-bot branch

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Fechin/reference.git
          git fetch upstream

      - name: Force sync main with upstream
        run: |
          git checkout main
          git reset --hard upstream/main  # Reset main to match upstream

      - name: Push to origin
        run: git push https://haruhadj:${{ secrets.PAT }}@github.com/haruhadj/reference.git main --force
