name: Mirror upstream

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch: # allow manual run

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false # we'll use a PAT instead
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "haruhadj-bot"
          git config user.email "haruhadj@gmail.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Fechin/reference.git
          git fetch upstream

      - name: Hard reset main to match upstream
        run: |
          git checkout main
          git reset --hard upstream/main

      - name: Push to your fork
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          git push https://haruhadj:${TOKEN}@github.com/haruhadj/reference.git main --force
